### ISSUE TITLE
Refresh only relevant parts of the digital clock

### ISSUE THREAD

**Issue by martinberlin** [martinberlin/epaper-weather-station#1]
Save HR / Min and temperature in NVS
Update only the relevant section on wake up:

**IF (nvs.hour == new.hour) THEN skip display.printf(“%d”, hour)**

![v1-digitalclock](https://user-images.githubusercontent.com/2692928/174425750-791e0c61-37a2-4b3b-8534-742a32e10560.jpeg)

**Comment by atc1441** [comment]
If you got a double buffer with the previous and new content you can simply make a rectangle around the smallest possible area that has changed. 
That way it is very dynamic and will work on any content

**Comment by martinberlin** [comment]
Hi Aaron!
Yes that 's a great idea. By the way I'm using the fast mode of Lovyan GFX library so it's [quite fast](https://twitter.com/martinfasani/status/1538215535007223814) (simulates 16 grays but is only doing a monochrome update). But the only issue is that even cleaning the area still leaves some nasty ghosting after 3 or 4 updates so I think every 5th update a full refresh should be enforced. 

Maybe I will just save in a 32 bit NVS the number of starts of the firmware and then make a full refresh like:

    if (boot_counter % 5 ==0) display.clearScreen();
    
Or something alike. Then it will be still fast while keeping the screen clean.

**Comment by martinberlin** [comment]
![6BFE439F-5F70-4338-A40F-BB100287D44A](https://user-images.githubusercontent.com/2692928/178134175-91639a8b-eedb-4219-aa6b-760a640e0ce1.jpeg)

**Comment by martinberlin** [comment]
DEXA-C097 + CINWRITE
![CinwritePCB](https://user-images.githubusercontent.com/2692928/179917874-a1dce4ac-cc5c-4921-9070-abb8d0a83d43.JPG)
